package multiThreading15;

public class PCProblem { // Producer-Consumer Problem in MultiThreading
	
	public static void main(String[] args) {
		
		Factory factory = new Factory();
		Producer producer = new Producer(factory);
		Consumer consumer = new Consumer(factory);
		
		producer.start();
		consumer.start();
		
	}
}

// Part of Output:
/*
PRODUCER HAS PRODUCED 387390 IN FACTORY
PRODUCER HAS PRODUCED 387391 IN FACTORY
PRODUCER HAS PRODUCED 387392 IN FACTORY
PRODUCER HAS PRODUCED 387393 IN FACTORY
PRODUCER HAS PRODUCED 387394 IN FACTORY
PRODUCER HAS PRODUCED 387395 IN FACTORY
CONSUMER HAS CONSUMED 387377 FROM FACTORY
CONSUMER HAS CONSUMED 387396 FROM FACTORY 
CONSUMER HAS CONSUMED 387396 FROM FACTORY
CONSUMER HAS CONSUMED 387396 FROM FACTORY
CONSUMER HAS CONSUMED 387396 FROM FACTORY
CONSUMER HAS CONSUMED 387396 FROM FACTORY
CONSUMER HAS CONSUMED 387396 FROM FACTORY
*/