package com.example.demo;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class SimpleController {
	
	@GetMapping("/admin")
	String display() {
		return "This is Admin page";
	}
	
	@GetMapping("/pub")
	String display2() {
		return "Anybody can access!"; 
	}
}


/* This is the default random password generated by spring security itself: (username: user)
	Using generated security password: 020033c6-5e8d-47cc-9492-088087a4b422

	This generated password is for development use only. Your security configuration must be updated before running your application in production.
*/

// Want to change???
// Change in application.properties 